// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "SwiftDate",
    platforms: [
        .macOS(.v10_10), .iOS(.v9), .watchOS(.v2), .tvOS(.v9)
    ],
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(name: "SwiftDate", targets: ["SwiftDate"]),
        .library(name: "SwiftDateStatic", type: .static, targets: ["SwiftDate"]),
        .library(name: "SwiftDateDynamic", type: .dynamic, targets: ["SwiftDate"])
    ],
    dependencies: [],
    targets: [
        .target(
            name: "SwiftDate",
            dependencies: [],
			resources: [
				.process("Formatters/RelativeFormatter/langs/af.json"),
                .process("Formatters/RelativeFormatter/langs/am.json"),
                .process("Formatters/RelativeFormatter/langs/ar_AE.json"),
                .process("Formatters/RelativeFormatter/langs/ar.json"),
                .process("Formatters/RelativeFormatter/langs/as.json"),
                .process("Formatters/RelativeFormatter/langs/be.json"),
                .process("Formatters/RelativeFormatter/langs/bg.json"),
                .process("Formatters/RelativeFormatter/langs/bn.json"),
                .process("Formatters/RelativeFormatter/langs/br.json"),
                .process("Formatters/RelativeFormatter/langs/bs-Cyrl.json"),
                .process("Formatters/RelativeFormatter/langs/bs.json"),
                .process("Formatters/RelativeFormatter/langs/ca.json"),
                .process("Formatters/RelativeFormatter/langs/cs.json"),
                .process("Formatters/RelativeFormatter/langs/cy.json"),
                .process("Formatters/RelativeFormatter/langs/da.json"),
                .process("Formatters/RelativeFormatter/langs/de.json"),
                .process("Formatters/RelativeFormatter/langs/dsb.json"),
                .process("Formatters/RelativeFormatter/langs/dz.json"),
                .process("Formatters/RelativeFormatter/langs/ee.json"),
                .process("Formatters/RelativeFormatter/langs/el.json"),
                .process("Formatters/RelativeFormatter/langs/en.json"),
                .process("Formatters/RelativeFormatter/langs/es_AR.json"),
                .process("Formatters/RelativeFormatter/langs/es_MX.json"),
                .process("Formatters/RelativeFormatter/langs/es_PY.json"),
                .process("Formatters/RelativeFormatter/langs/es_US.json"),
                .process("Formatters/RelativeFormatter/langs/es.json"),
                .process("Formatters/RelativeFormatter/langs/et.json"),
                .process("Formatters/RelativeFormatter/langs/eu.json"),
                .process("Formatters/RelativeFormatter/langs/fa.json"),
                .process("Formatters/RelativeFormatter/langs/fi.json"),
                .process("Formatters/RelativeFormatter/langs/fil.json"),
                .process("Formatters/RelativeFormatter/langs/fo.json"),
                .process("Formatters/RelativeFormatter/langs/fr_CA.json"),
                .process("Formatters/RelativeFormatter/langs/fr.json"),
                .process("Formatters/RelativeFormatter/langs/fur.json"),
                .process("Formatters/RelativeFormatter/langs/fy.json"),
                .process("Formatters/RelativeFormatter/langs/ga.json"),
                .process("Formatters/RelativeFormatter/langs/gd.json"),
                .process("Formatters/RelativeFormatter/langs/gl.json"),
                .process("Formatters/RelativeFormatter/langs/gu.json"),
                .process("Formatters/RelativeFormatter/langs/he.json"),
                .process("Formatters/RelativeFormatter/langs/hi.json"),
                .process("Formatters/RelativeFormatter/langs/hr.json"),
                .process("Formatters/RelativeFormatter/langs/hsb.json"),
                .process("Formatters/RelativeFormatter/langs/hu.json"),
                .process("Formatters/RelativeFormatter/langs/hy.json"),
                .process("Formatters/RelativeFormatter/langs/id.json"),
                .process("Formatters/RelativeFormatter/langs/is.json"),
                .process("Formatters/RelativeFormatter/langs/it.json"),
                .process("Formatters/RelativeFormatter/langs/ja.json"),
                .process("Formatters/RelativeFormatter/langs/jgo.json"),
                .process("Formatters/RelativeFormatter/langs/ka.json"),
                .process("Formatters/RelativeFormatter/langs/kea.json"),
                .process("Formatters/RelativeFormatter/langs/kk.json"),
                .process("Formatters/RelativeFormatter/langs/kl.json"),
                .process("Formatters/RelativeFormatter/langs/km.json"),
                .process("Formatters/RelativeFormatter/langs/kn.json"),
                .process("Formatters/RelativeFormatter/langs/ko.json"),
                .process("Formatters/RelativeFormatter/langs/kok.json"),
                .process("Formatters/RelativeFormatter/langs/ksh.json"),
                .process("Formatters/RelativeFormatter/langs/ky.json"),
                .process("Formatters/RelativeFormatter/langs/lb.json"),
                .process("Formatters/RelativeFormatter/langs/lkt.json"),
                .process("Formatters/RelativeFormatter/langs/lo.json"),
                .process("Formatters/RelativeFormatter/langs/lt.json"),
                .process("Formatters/RelativeFormatter/langs/lv.json"),
                .process("Formatters/RelativeFormatter/langs/mk.json"),
                .process("Formatters/RelativeFormatter/langs/ml.json"),
                .process("Formatters/RelativeFormatter/langs/mn.json"),
                .process("Formatters/RelativeFormatter/langs/mr.json"),
                .process("Formatters/RelativeFormatter/langs/ms.json"),
                .process("Formatters/RelativeFormatter/langs/mt.json"),
                .process("Formatters/RelativeFormatter/langs/my.json"),
                .process("Formatters/RelativeFormatter/langs/mzn.json"),
                .process("Formatters/RelativeFormatter/langs/nb.json"),
                .process("Formatters/RelativeFormatter/langs/ne.json"),
                .process("Formatters/RelativeFormatter/langs/nl.json"),
                .process("Formatters/RelativeFormatter/langs/nn.json"),
                .process("Formatters/RelativeFormatter/langs/or.json"),
                .process("Formatters/RelativeFormatter/langs/pa.json"),
                .process("Formatters/RelativeFormatter/langs/pl.json"),
                .process("Formatters/RelativeFormatter/langs/ps.json"),
                .process("Formatters/RelativeFormatter/langs/pt.json"),
                .process("Formatters/RelativeFormatter/langs/ro.json"),
                .process("Formatters/RelativeFormatter/langs/ru.json"),
                .process("Formatters/RelativeFormatter/langs/sah.json"),
                .process("Formatters/RelativeFormatter/langs/sd.json"),
                .process("Formatters/RelativeFormatter/langs/se_FI.json"),
                .process("Formatters/RelativeFormatter/langs/se.json"),
                .process("Formatters/RelativeFormatter/langs/si.json"),
                .process("Formatters/RelativeFormatter/langs/sk.json"),
                .process("Formatters/RelativeFormatter/langs/sl.json"),
                .process("Formatters/RelativeFormatter/langs/sq.json"),
                .process("Formatters/RelativeFormatter/langs/sr_Latn.json"),
                .process("Formatters/RelativeFormatter/langs/sr.json"),
                .process("Formatters/RelativeFormatter/langs/sv.json"),
                .process("Formatters/RelativeFormatter/langs/sw.json"),
                .process("Formatters/RelativeFormatter/langs/ta.json"),
                .process("Formatters/RelativeFormatter/langs/te.json"),
                .process("Formatters/RelativeFormatter/langs/th.json"),
                .process("Formatters/RelativeFormatter/langs/ti.json"),
                .process("Formatters/RelativeFormatter/langs/tk.json"),
                .process("Formatters/RelativeFormatter/langs/to.json"),
                .process("Formatters/RelativeFormatter/langs/tr.json"),
                .process("Formatters/RelativeFormatter/langs/ug.json"),
                .process("Formatters/RelativeFormatter/langs/uk.json"),
                .process("Formatters/RelativeFormatter/langs/ur_IN.json"),
                .process("Formatters/RelativeFormatter/langs/ur.json"),
                .process("Formatters/RelativeFormatter/langs/uz_Cyrl.json"),
                .process("Formatters/RelativeFormatter/langs/uz.json"),
                .process("Formatters/RelativeFormatter/langs/vi.json"),
                .process("Formatters/RelativeFormatter/langs/wae.json"),
                .process("Formatters/RelativeFormatter/langs/yi.json"),
                .process("Formatters/RelativeFormatter/langs/yue_Hans.json"),
                .process("Formatters/RelativeFormatter/langs/yue_Hant.json"),
                .process("Formatters/RelativeFormatter/langs/zh_Hans_HK.json"),
                .process("Formatters/RelativeFormatter/langs/zh_Hans_MO.json"),
                .process("Formatters/RelativeFormatter/langs/zh_Hans_SG.json"),
                .process("Formatters/RelativeFormatter/langs/zh_Hans.json"),
                .process("Formatters/RelativeFormatter/langs/zh_Hant_HK.json"),
                .process("Formatters/RelativeFormatter/langs/zh_Hant.json"),
                .process("Formatters/RelativeFormatter/langs/zh.json"),
                .process("Formatters/RelativeFormatter/langs/zu.json"),
			]),
        .testTarget(
            name: "SwiftDateTests",
            dependencies: ["SwiftDate"])
    ]
)
